#!/bin/sh

PROGRAM=/usr/local/lib/swatchbooker/swatchbooker.pyw
PYTHON=`which python`
export PYTHONPATH=/usr/local/lib/python3.9/dist-packages:/usr/local/lib/python3.9/dist-packages/swatchbook:$PYTHONPATH

$PYTHON $PROGRAM ;
