#!/bin/sh

PROGRAM=/opt/SwatchBooker/lib/swatchbooker/swatchbooker.pyw
PYTHON=`which python`
export PYTHONPATH=/opt/SwatchBooker/lib/python3.9/site-packages:/opt/SwatchBooker/lib/python3.9/site-packages/swatchbook:$PYTHONPATH

$PYTHON $PROGRAM ;
